### PR TITLE
list component added

### PR DESCRIPTION
**Pull request by Shinde-Sandesh**
image

### CODE REVIEW

**Review by keyurshah339 — APPROVED** [review]
no changes needed
go ahead with merge

**Comment by Shinde-Sandesh** [comment]
> no changes needed go ahead with merge

Thank you for your review

**Review by iHarryD — APPROVED** [review]
Can merge. Everything looks good.

**Review by keyurshah339 — COMMENTED** [review]
proper naming convention used
good to merge

**Pull request merged**
